const medRec = {
  Aymen: [
    {
      patient: 'ea50ac55-ef4e-43d3-b753-36a86db7b17d',
      smoking: true,
      chewing: false,
      injection: true,
      oldSmoker: true,
      alcohol: false,
      medication_consumption: false,
      smokingNumberUnits: 22,
      chewingNumberUnits: 0,
      injectionNumbernits: 11,
      ageFc: '15',
      duration: '8',
      medication: '',
      familySituation: 'Married',
      bloodType: 'A+',
      social_number: '36',
      date: '',
      wieght: '75',
      height: '1.80',
      hearing_right: 'good',
      hearing_left: 'bad',
      visual_acuity_with_correction_left: 'bad',
      visual_acuity_with_correction_right: 'ba',
      visual_acuity_without_correction_left: 'khayrett',
      visual_acuity_without_correction_right: 'chweya chweya',
      skin_state: 'good',
      skin_exam: '',
      ophtalmological_state: 'mahnech',
      ophtalmological_exam: '',
      respiratory_state: 'labess',
      respiratory_exam: '',
      cardiovascular_state: '3ey l makhlou9',
      cardiovascular_exam: '',
      digestive_state: '',
      digestive_exam: '',
      aptitude: '',
      reason: '',
      orl_state: '',
      orl_exam: '',
      locomotor_case: '',
      locomotor_exam: '',
    },
  ],
};
export default medRec;
