const medicaments = [
  { name: 'ABILIFY 15MG COMP. B/28' },
  { name: 'ABUFENE 400MG COMP. B/30' },
  { name: 'ACEPRAL 500MG COMP. B/20 ' },
  { name: 'ACIDRINE 2,50MG/250MG/200MG COMP. A CROQ. B/40' },
  { name: 'BEPANTHENE 100MG COMP. B/20' },
  { name: 'BETABIO 2MG COMP. DISPERS. SEC. PILULIER DE 20' },
  { name: 'ACEPRAL 500MG COMP. B/20 ' },
  { name: 'BETACROVIS 0,5MG/ML (0,05%) SOL.BUV. GTTES FL/40ML' },
  { name: 'GALARA 300MG GLES' },
  { name: 'MAXILODRE (3mg,3500UI,6000UI/ml) COLLY. EN SOL. FL./3ML' },
  { name: 'MAXILASE 20 000 U CEIP/100ML SIROP ENF. ET AD. FL/125ML' },
  { name: 'MEDROL 16MG COMP. B/20' },
  { name: 'ABUFENE 400MG COMP. B/30' },
  { name: 'NADLORIC 100MG COMP. B/30' },
  { name: 'OFLAX 400MG COMP. B/10' },
  { name: 'OLANZA 5MG COMP. PELLI. B/28	' },
  { name: 'PANADOL 1G COMP. PELLI. SEC. B/08	' },
  { name: 'PANADOL EXTRA 500MG/65MG COMP. PELLI. B/16' },
  { name: 'PARACETAMOL BIOCARE 100MG GRLES. P. SOL. BUV. SACH.-DOSE B/12' },
  { name: 'PARACETAMOL BIOCARE 300MG GRLES. P. SOL. BUV. SACH.-DOSE B/12' },
  { name: 'PARALGAN 1000MG SUPPO. B/10' },
  { name: 'PARALGAN 120MG SUPPO. B/10' },
  { name: 'QUINOX 500MG COMP. ENRO. B/10' },
  { name: 'TALOPREX 10MG COMP. PELLI. B/30' },
  { name: 'VALSARTAL 80MG COMP. PELLI. SEC. B/30' },
  { name: 'VALEX 160MG COMP. PELLI. B/30 ' },
  { name: 'LAVIDA 1MG COMP. B/30	' },
  { name: 'LAROXYL 50MG COMP. PELLI. B/20' },
  { name: 'LARGACTIL 100MG COMP.PELLI. SEC. B/30' },
  { name: 'RAMIPRIL IVAL 2,5MG COMP. SEC. B/30' },
];
export default medicaments;
